---
global:
  gc: true
  indexerConfig:
    type: local             # Indexer type
    createTarball: true     # Create tarball with metrics
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: 10s
jobs:
  - name: index-stuff
    namespace: index-stuff
    jobIterations: 100
    qps: 10
    burst: 10
    namespacedIterations: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 10s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: templates/deploy.yml
        replicas: 2

      - objectTemplate: templates/secret.yml
        replicas: 1

