apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Replica }}
spec:
  replicas: {{ .podReplicas }}
  selector:
    matchLabels:
      app: nginx-{{ .Replica }}
  template:
    metadata:
      labels:
        app: nginx-{{ .Replica }}
    spec:
      containers:
      - image: {{ .image }}
        name: nginx

