---
global:
  gc: false
jobs:
  - name: create-stuff
    namespace: create-stuff
    jobIterations: 50
    qps: 5
    burst: 5
    namespacedIterations: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 10s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: templates/deploy.yml
        replicas: 2
        inputVars:
          podReplicas: 2
          image: quay.io/cloud-bulldozer/nginx:latest


  - name: delete-stuff
    jobIterations: 10
    qps: 3
    burst: 3
    jobType: delete
    waitForDeletion: true
    objects:

      - labelSelector: 
          kube-burner-job: create-stuff
        kind: deployment
        apiVersion: apps/v1