apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Replica }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-{{ .Replica }}
  template:
    metadata:
      labels:
        app: nginx-{{ .Replica }}
    spec:
      containers:
      - image: quay.io/cloud-bulldozer/nginx:latest
        name: nginx

